/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Direct-Print.h
 #	source generated by 4D Plugin Wizard
 #	Project : Direct Print
 #	author : miyako
 #	2020/08/13
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_DIRECT_PRINT_H
#define PLUGIN_DIRECT_PRINT_H

#include "4DPluginAPI.h"

#if VERSIONWIN
// Don't rely on <windows.h> transitively pulling this in - the vendored
// 4D Plugin API SDK's C_TYPES.h now defines WIN32_LEAN_AND_MEAN before its
// own #include <windows.h>, which suppresses windows.h's normal automatic
// inclusion of <winspool.h> (OpenPrinter, DOC_INFO_1, StartDocPrinter,
// StartPagePrinter, WritePrinter, EndPagePrinter, EndDocPrinter,
// ClosePrinter). winspool.lib is already linked via the .vcxproj, so this
// header is the only piece that was missing.
#include <winspool.h>
#endif

#include "C_LONGINT.h"
#include "C_TEXT.h"

#pragma mark -

void PRINT_BLOB(PA_PluginParameters params);
void PRINT_BLOB_ARRAY(PA_PluginParameters params);

#define ERR_OPEN_PRINTER -1
#define ERR_START_DOC_PRINTER -2
#define ERR_WRITE_PRINTER -3
#define ERR_END_DOC_PRINTER -4
#define ERR_END_PAGE_PRINTER -5
#define ERR_CLOSE_PRINTER -6
#define ERR_START_PAGE_PRINTER -7

#define ERR_PM_CREATE_SESSION -11
#define ERR_PM_CREATE_PRINT_SETTINGS -12
#define ERR_PM_SET_CURRENT_PM_PRINTER -13
#define ERR_PM_CREATE_PAGE_FORMAT -14
#define ERR_PM_SESSION_DEFAULT_PAGE_FORMAT -15
#define ERR_PM_SESSION_DEFAULT_PRINT_SETTINGS -16
#define ERR_PM_PRINTER_PRINT_WITH_FILE -17
#define ERR_PM_PRINTER_NOT_FOUND -18

#endif /* PLUGIN_DIRECT_PRINT_H */
