/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Direct Print
 #	author : miyako
 #	2016/08/29
 #
 # --------------------------------------------------------------------------------*/



// --- Direct Print
void PRINT_BLOB(sLONG_PTR *pResult, PackagePtr pParams);
void PRINT_BLOB_ARRAY(sLONG_PTR *pResult, PackagePtr pParams);

#define ERR_OPEN_PRINTER -1
#define ERR_START_DOC_PRINTER -2
#define ERR_WRITE_PRINTER -3
#define ERR_END_DOC_PRINTER -4